version: '3.5'

services:

  todo-api-go:
    build:
      context: ../..
    image: todo-api-go
    container_name: todo-api-go
    restart: always
    networks:
      - todo-api-go
    ports:
      - "8080:8080"
    environment:
      DB_TYPE: "postgres"
      DB_DSN: "host={{.Host}} port={{.Port}} dbname={{.Database}} user={{.User}} password={{.Pass}} sslmode=disable"
      DB_HOST: "todo-api-go-postgres"
      DB_PORT: "5432"
      DB_DATABASE: "postgres"
      DB_USER: "postgres"
      DB_PASS: "p455w0rd"
      DB_AUTO_MIGRATE: "false"

networks:
  todo-api-go:
    name: todo-api-go
