version: "2.4"

volumes:
  todo-api-go-signoz-alertmanager-data:
    driver: local
  todo-api-go-signoz-clickhouse-data:
    driver: local
  todo-api-go-signoz-service-data:
    driver: local
  todo-api-go-signoz-zookeeper-data:
    driver: local

services:
  zookeeper-1:
    container_name: signoz-zookeeper-1
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
      ZOO_AUTOPURGE_INTERVAL: '1'
      ZOO_SERVER_ID: '1'
    hostname: zookeeper-1
    image: bitnami/zookeeper:$ZOOKEEPER_VERSION
    ports:
    - published: 2181
      target: 2181
    - published: 2888
      target: 2888
    - published: 3888
      target: 3888
    user: root
    volumes:
    - todo-api-go-signoz-zookeeper-data:/bitnami/zookeeper:rw
    networks:
      - todo-api-go

  alertmanager:
    container_name: signoz-alertmanager
    image: signoz/alertmanager:$ALERTMANAGER_VERSION
    command:
    - --queryService.url=http://query-service:8085
    - --storage.path=/data
    depends_on:
      query-service:
        condition: service_healthy
    restart: on-failure
    volumes:
    - todo-api-go-signoz-alertmanager-data:/data:rw
    networks:
      - todo-api-go

  clickhouse:
    container_name: signoz-clickhouse
    image: clickhouse/clickhouse-server:$CLICKHOUSE_VERSION
    depends_on:
      zookeeper-1:
        condition: service_started
    healthcheck:
      interval: 30s
      retries: 3
      test:
      - CMD
      - wget
      - --spider
      - -q
      - localhost:8123/ping
      timeout: 5s
    hostname: clickhouse
    logging:
      options:
        max-file: '3'
        max-size: 50m
    ports:
    - published: 9000
      target: 9000
    - published: 8123
      target: 8123
    - published: 9181
      target: 9181
    restart: on-failure
    tty: true
    ulimits:
      nofile:
        hard: 262144
        soft: 262144
      nproc: 65535
    volumes:
    - todo-api-go-signoz-clickhouse-data:/var/lib/clickhouse:rw
    - ./clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.xml:rw
    - ./clickhouse/clickhouse-users.xml:/etc/clickhouse-server/users.xml:rw
    - ./clickhouse/custom-function.xml:/etc/clickhouse-server/custom-function.xml:rw
    - ./clickhouse/clickhouse-cluster.xml:/etc/clickhouse-server/config.d/cluster.xml:rw
    - ./clickhouse/user_scripts:/var/lib/clickhouse/user_scripts:rw
    networks:
      - todo-api-go

  query-service:
    container_name: signoz-query-service
    image: signoz/query-service:$SIGNOZ_VERSION
    command:
    - -config=/root/config/prometheus.yml
    depends_on:
      clickhouse:
        condition: service_healthy
      otel-collector-migrator:
        condition: service_completed_successfully
    environment:
      ALERTMANAGER_API_PREFIX: http://alertmanager:9093/api/
      ClickHouseUrl: tcp://clickhouse:9000/?database=signoz_traces
      DASHBOARDS_PATH: /root/config/dashboards
      DEPLOYMENT_TYPE: docker-standalone-amd
      GODEBUG: netdns=go
      SIGNOZ_LOCAL_DB_PATH: /var/lib/signoz/signoz.db
      STORAGE: clickhouse
      TELEMETRY_ENABLED: "true"
    healthcheck:
      interval: 30s
      retries: 3
      test:
      - CMD
      - wget
      - --spider
      - -q
      - localhost:8080/api/v1/health
      timeout: 5s
    restart: on-failure
    volumes:
    - ./query-service/prometheus.yml:/root/config/prometheus.yml:rw
    - ./query-service/dashboards:/root/config/dashboards:rw
    - todo-api-go-signoz-service-data:/var/lib/signoz:rw
    networks:
      - todo-api-go

  frontend:
    container_name: signoz-frontend
    image: signoz/frontend:$SIGNOZ_VERSION
    depends_on:
      alertmanager:
        condition: service_started
      query-service:
        condition: service_started
    ports:
    - published: 3301
      target: 3301
    restart: on-failure
    volumes:
    - ./nginx/nginx-config.conf:/etc/nginx/conf.d/default.conf:rw
    networks:
      - todo-api-go

  otel-collector:
    container_name: signoz-otel-collector
    image: signoz/signoz-otel-collector:$OTEL_COLLECTOR_VERSION
    command:
    - --config=/etc/otel-collector-config.yaml
    - --manager-config=/etc/manager-config.yaml
    - --copy-path=/var/tmp/collector-config.yaml
    - --feature-gates=-pkg.translator.prometheus.NormalizeName
    depends_on:
      clickhouse:
        condition: service_healthy
      otel-collector-migrator:
        condition: service_completed_successfully
      query-service:
        condition: service_healthy
    environment:
      DOCKER_MULTI_NODE_CLUSTER: "false"
      LOW_CARDINAL_EXCEPTION_GROUPING: "false"
      OTEL_RESOURCE_ATTRIBUTES: host.name=signoz-host,os.type=linux
    ports:
    - published: 4317
      target: 4317
    - published: 4318
      target: 4318
    restart: on-failure
    user: root
    volumes:
    - ./otel-collector/otel-collector-config.yaml:/etc/otel-collector-config.yaml:rw
    - ./otel-collector/otel-collector-opamp-config.yaml:/etc/manager-config.yaml:rw
    - /var/lib/docker/containers:/var/lib/docker/containers:ro
    networks:
      - todo-api-go

  otel-collector-migrator:
    container_name: otel-migrator
    image: signoz/signoz-schema-migrator:$OTEL_COLLECTOR_VERSION
    command:
    - --dsn=tcp://clickhouse:9000
    depends_on:
      clickhouse:
        condition: service_healthy
    networks:
      - todo-api-go

  logspout:
    container_name: signoz-logspout
    image: gliderlabs/logspout:$LOGSPOUT_VERSION
    command: syslog+tcp://otel-collector:2255
    depends_on:
      otel-collector:
        condition: service_started
    restart: on-failure
    volumes:
    - /etc/hostname:/etc/host_hostname:ro
    - /var/run/docker.sock:/var/run/docker.sock:rw
    networks:
      - todo-api-go

networks:
  todo-api-go:
    name: todo-api-go
